/* Generated By:JavaCC: Do not edit this line. quik_parserConstants.java */
package java_quik;

public interface quik_parserConstants {

  int EOF = 0;
  int LBRACE = 5;
  int RBRACE = 6;
  int Lkakko = 7;
  int Rkakko = 8;
  int sk2 = 9;
  int sk = 10;
  int program = 11;
  int query = 12;
  int debug = 13;
  int mediator = 14;
  int ontology = 15;
  int subsumption = 16;
  int rule = 17;
  int end = 18;
  int test = 19;
  int SHARP = 20;
  int r = 21;
  int g = 22;
  int b = 23;
  int STREAM = 24;
  int WQUOTE = 25;
  int ATOM = 26;
  int DIGIT = 27;
  int URL = 28;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";;\"",
    "\";\"",
    "\"&program\"",
    "\"&query\"",
    "\"&debug\"",
    "\"&mediator\"",
    "\"&ontology\"",
    "\"&subsumption\"",
    "\"&rule\"",
    "\"&end\"",
    "\"test1\"",
    "\"#\"",
    "\"r=\"",
    "\"g=\"",
    "\"b=\"",
    "\"stream\"",
    "\" \\\" \"",
    "<ATOM>",
    "<DIGIT>",
    "<URL>",
    "\".\"",
    "\"<=\"",
    "\"@\"",
    "\",\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
  };

}
